export const dummy = [
  {
    id: "c1",
    category: "상품권",
    title: "문화상품권 10% 할인",
    writer: "김인하",
    content: "티몬에서 10% 할인합니다.",
    hit: 30,
    like: 10,
    comments: [],
    date: "2022-04-20",
  },
  {
    id: "c2",
    category: "포인트적립",
    title: "네이버 포인트 적립",
    writer: "박인하",
    content: "네페 포인트 10원 적립 링크",
    hit: 353,
    like: 190,
    comments: [],
    date: "2022-04-26",
  },
  {
    id: "c3",
    category: "알뜰팁",
    title: "한달 10만원으로 생활해 봤어요.",
    writer: "최인하",
    content: "동해물과 백두산이 마르고 닳도록",
    hit: 95,
    like: 11,
    comments: [],
    date: "2022-04-28",
  },
  {
    id: "c4",
    category: "핫딜",
    title: "라면 10개 6000원",
    writer: "양희연",
    content: "엄청 싸네요. 얼른 구매하세요",
    hit: 530,
    like: 106,
    comments: [],
    date: "2022-04-30",
  },
  {
    id: "c5",
    category: "금융상품",
    title: "대학생 신용카드 추천",
    writer: "김지원",
    content: "대학생도 신용카드 만들 수 있어요",
    hit: 10,
    like: 13,
    comments: [],
    date: "2022-05-02",
  },
  {
    id: "c6",
    category: "상품권",
    title: "가계부 커뮤니티",
    writer: "정인하",
    content: "거친 돌이 다듬어져 조각이 되듯",
    hit: 35,
    like: 5,
    comments: [],
    date: "2022-05-05",
  },
];
