export const boardData = [
  {
    id: 1,
    title: "인하대 종설",
    author: "김인하",
    content: "게시판",
    lastedit: "2022-04-20",
  },
  {
    id: 2,
    title: "소셜가계부",
    author: "박인하",
    content: "게시판에 글을 쓰자",
    lastedit: "2022-04-26",
  },
  {
    id: 3,
    title: "애국가",
    author: "최인하",
    content: "동해물과 백두산이 마르고 닳도록",
    lastedit: "2022-04-28",
  },
  {
    id: 4,
    title: "소셜가계부",
    author: "양희연",
    content: "게시판에 글을 쓰자",
    lastedit: "2022-04-30",
  },
  {
    id: 5,
    title: "컴퓨터공학",
    author: "김지원",
    content: "컴퓨터공학과 인하대",
    lastedit: "2022-05-02",
  },
  {
    id: 6,
    title: "가계부 커뮤니티",
    author: "정인하",
    content: "거친 돌이 다듬어져 조각이 되듯",
    lastedit: "2022-05-05",
  },
  {
    id: 7,
    title: "인하대 종설",
    author: "황지윤",
    content: "게시판",
    lastedit: "2022-05-10",
  },
  {
    id: 8,
    title: "소셜가계부",
    author: "서현주",
    content: "게시판에 글을 쓰자",
    lastedit: "2022-05-20",
  },
  {
    id: 9,
    title: "인하대 종설",
    author: "김인하",
    content: "게시판",
    lastedit: "2022-05-20",
  },
  {
    id: 10,
    title: "소셜가계부",
    author: "박인하",
    content: "게시판에 글을 쓰자",
    lastedit: "2022-05-23",
  },
];
