export const dummy = [
  {
    id: 1,
    date: "2022-01-30",
    category: "교통/차량",
    content: "버스비",
    account: -4000,
    transactionType: "지출",
    memo: "버스비",
  },
  {
    id: 2,
    date: "2022-01-31",
    category: "용돈",
    content: "용돈",
    account: 12000,
    transactionType: "수입",
    memo: "",
  },
  {
    id: 3,
    date: "2022-02-06",
    category: "문화비",
    content: "서적구매",
    account: -25000,
    transactionType: "지출",
    memo: "컴퓨터공학입문서 구입",
  },
  {
    id: 4,
    date: "2022-02-18",
    category: "식비",
    content: "외식비",
    account: -52000,
    transactionType: "지출",
    memo: "외식",
  },
];
